compiler: g++
dist: xenial
language: cpp
os: linux

stages:
  - build
  - test
  - deploy

jobs: 
  include: 
    - stage: build
      env:
        - TARGET=armv7
        - TARGET=x86_64
      script: sleep 1; echo "build $TARGET "
    - script: export TARGET=x86_64;sleep 1; echo "build x86_64"
    - stage: test
      name: "Unit Tests" 
      script: sleep 1; echo "test 1"
    - script: sleep 1; echo "test 2"
      name: "Integration Tests" 
    - stage: deploy
      name: "Deploy to Github" 
      script: sleep 1; echo "deploy"

