compiler: g++
dist: xenial
language: cpp
os: linux

stages:
  - build
  - test
  - deploy

jobs: 
  include: 
    - stage: build
      script: sleep 1; echo "build armv7 "
    - script: sleep 1; echo "build x86_64"
    - stage: test
      script: sleep 1; echo "test 1 "
    - script: sleep 1; echo "test 2"
    - script: sleep 1; echo "test 3"
    - stage: deploy
      script: sleep 1; echo "deploy "

