compiler: g++
dist: xenial
language: cpp
os: linux

jobs: 
  include: 
    - stage: build
      script: sleep 5; echo "build stage"
    - stage: test
      script: sleep 10; echo "test stage"
    - script: sleep 5

