language: cpp
os: linux
dist: trusty
sudo: required
compiler: g++

before_install:
    - sudo pip install codecov

script: 
    - cd Build &&  ./build.sh
    - ./get-code-cov.sh
    - codecov

after_success:
    - bash <(curl -s https://codecov.io/bash)
