language: cpp
os: linux
dist: trusty
sudo: required
compiler: g++

before_install:
    - sudo apt-get install libssl-dev

install:
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
    - cd Build &&  ./build.sh
    - ./get-code-cov.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
