language: cpp
os: linux
dist: trusty
sudo: required
compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo pip install codecov

install: 
    # C++11
    - sudo apt-get install g++-5
    # Codecov
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script: 
    - cd Build &&  ./build.sh
    - ./get-code-cov.sh
    - codecov

after_success:
    - bash <(curl -s https://codecov.io/bash)
