compiler: g++
dist: xenial
language: cpp
os: linux

stages:
  - build
  - test
  - deploy

env:
  - TARGET=armv7
  - TARGET=x86_64
        
jobs: 
  include: 
    - stage: build
      script: sleep 5; echo "build armv7 "
      name: "Build $TARGET"
    - script: sleep 5; echo "build x86_64"
      name: "Build $TARGET"
    - stage: test
      script: sleep 5; echo "test 1 "
      name: "Test $TARGET"
    - script: sleep 5; echo "test 2"
      name: "Test $TARGET"
    - stage: deploy
      script: sleep 5; echo "deploy "

